name: Build and deploy package

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Test with dotnet
      run: dotnet test

    - name: Create the Package
      run: dotnet pack --configuration Release

    - name: Set up secret file
      run: echo ${{secrets.NUGET_TOKEN}} | sed 's/./& /g'

      - name: Publish the Package
      run: dotnet nuget push "GiacomoMoneyExtension/bin/Release/*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/rafaelgiacomo/index.json --skip-duplicate

    # - name: Publish the Package
    #   run: dotnet nuget push "GiacomoMoneyExtension/bin/Release/*.nupkg" -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json