name: Build and deploy package

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Test with dotnet
      run: dotnet test

    - name: Create the Package
      run: dotnet pack --configuration Release

    - name: Set up secret file
      run: echo ${{secrets.NUGET_TOKEN}} | sed 's/./& /g'

    - name: Publish the Package
      run: dotnet nuget push "MoneyExtension/bin/Release/*.nupkg" --api-key ${{secrets.NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json